#loggers
log_name: ./output/application.log
log_level: DEBUG
#where to send
URL: http://localhost
port_send: 8000
#crons
#cron: "CRON_TZ: UTC 37 14 * * *"
cron: "* * * * *"
#cron_add_message: "*/10 * * * *"
cron_add_message: "* * * * *"
#postgres
  [store]
host: 127.0.0.1
port: 5432
database: work
user: nefremov
password: Aa174683Aa